name = "Flight"
uuid = "e329eb8f-69f3-4234-a468-5e3889a58643"
authors = ["Miguel Alonso <miguel883@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ImGuiGLFWBackend = "623d79b3-9695-4e60-bd7e-2a5aabaa6933"
ImGuiOpenGLBackend = "9d0819b4-44e7-43a2-ad03-8fb999128168"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
AbstractTrees = "0.4.4"
CImGui = "1.89.0"
ComponentArrays = "0.15.5"
ControlSystems = ">=1.8.2"
DataStructures = "0.18.15"
DiffEqCallbacks = "2.34.0"
FiniteDiff = ">=2.21.1"
GLFW = "3.4.1"
GR = ">=0.72.10"
HDF5 = ">=0.17.1"
ImGuiGLFWBackend = "0.2.0"
ImGuiOpenGLBackend = "0.2.0"
Interpolations = ">=0.14.7"
LaTeXStrings = "1.3.1"
NLopt = "1.0.0"
OrdinaryDiffEq = ">=6.59.2"
Plots = "1.39.0"
RecursiveArrayTools = ">=2.38.10"
Reexport = "1.2.2"
Roots = "2.0.22"
SHA = "0.7.0"
SciMLBase = ">=2.8.2"
StaticArrays = "1.7.0"
StructArrays = "0.6.16"
Trapz = "2.0.3"
UnPack = "1.0.2"
julia = "1.10"
