name = "FlightLib"
uuid = "217868e0-669b-4069-89f9-42760bf46690"
version = "0.1.0"
authors = ["Miguel Alonso <miguel883@gmail.com>"]

[workspace]
projects = ["test"]

[deps]
CImGui = "5d785b6c-b76f-510e-a07c-3070796c7e87"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
FlightCore = "e3cc1ee6-15ac-4fef-96b3-1947582bf537"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[sources]
FlightCore = {path = "../FlightCore"}

[compat]
CImGui = "6"
ComponentArrays = "0.15.29"
ControlSystems = "1.15"
DataStructures = "0.19"
EnumX = "1.0.5"
FiniteDiff = "2.28.1"
HDF5 = "0.17"
Interpolations = "0.16"
JSON3 = "1.14.3"
LaTeXStrings = "1.4"
NLopt = "1.2.1"
Plots = "1.40.19"
RecursiveArrayTools = "3.37"
Reexport = "1.2.2"
RobustAndOptimalControl = "0.4.45"
Roots = "2.2.10"
StaticArrays = "1.9.14"
StructArrays = "0.7"
StructTypes = "1.11.0"
Trapz = "2.0.3"
julia = "1.12"
