name = "FlightDesign"
uuid = "f0790872-85e1-4f6d-a32c-46d55985dfbe"
version = "0.1.0"
authors = ["Miguel Alonso <miguel883@gmail.com>"]

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Flight = "e329eb8f-69f3-4234-a468-5e3889a58643"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[sources]
Flight = {path = ".."}

[compat]
ComponentArrays = "0.15.32"
ControlSystems = "1.15.2"
HDF5 = "0.17.2"
Interpolations = "0.16.2"
LinearAlgebra = "1.12.0"
Logging = "1.11.0"
Plots = "1.41.6"
RobustAndOptimalControl = "0.4.49"
StaticArrays = "1.9.16"
StructArrays = "0.7.2"
