[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Flight = "e329eb8f-69f3-4234-a468-5e3889a58643"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[sources]
Flight = {path = ".."}

[compat]
ControlSystems = "1.15.2"
Plots = "1.41.6"
RobustAndOptimalControl = "0.4.49"
